blank_issues_enabled: false
contact_links:
  - name: Day Counter Plus Wiki
    url: https://github.com/3lbash3/Day-Counter-Plus/wiki
    about: Check the wiki for guides and documentation before opening an issue.
